version: "3"

services:
  jena-fuseki:
    image: secoresearch/fuseki
    hostname: jena-fuseki
    container_name: jena-fuseki
    ports:
      - 3030:3030
    environment: 
      - ADMIN_PASSWORD=admin
      - ENABLE_DATA_WRITE=true
      - ENABLE_UPDATE=true
      - ENABLE_UPLOAD=true
  jena-fuseki-sidecar-setup:
    build: ..
    environment: 
      - JENA_FUSEKI=jena-fuseki:3030
      - DATASET=foaf
      - USERNAME=admin
      - PASSWORD=admin
    volumes: 
      - "./init:/init"
